runtime: php55
api_version: 1

handlers:
- url: /(.+\.php)$
  script: \1

- url: /static
  static_dir: static
  
- url: /bootstrap
  static_dir: bootstrap

- url: /img
  static_dir: img  

- url: /.*
  script: index.php